version: '3'
services:
  mongodb:
    image: "mongo:4"
    restart: unless-stopped
    command: --nojournal --maxConns 64
    volumes:
      - db:/data/db
    ports:
      - "27017:27017"

  histomicsui:
    environment:
      - GIRDER_MONGO_URI=mongodb://mongodb:27017/girder
    command: girder serve -H 0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - assetstore:/assetstore
      - ./girder_worker/girder_worker:/opt/girder_worker/girder_worker
      - ./slicer_cli_web/slicer_cli_web:/opt/slicer_cli_web/slicer_cli_web
      - ./large_image/girder:/opt/large_image/girder
      - ./large_image/girder_annotation:/opt/large_image/girder_annotation
      - ./HistomicsUI/histomics:/opt/HistomicsUI/histomics
    build:
      context: .
      dockerfile: ./histomicsui.Dockerfile

volumes:
  db:
  assetstore:
